
const data = {
    text: {
        drink_info: {
            blank: '',
            tequila: {
                en: 'tequila',
                ru: 'текила',
                fi: 'tequila',
                et: 'tequila',
            },
            gin: {
                en: 'gin',
                ru: 'джин',
                fi: 'gin',
                et: 'džinn',
            },

            size: {
                en: 'size',
                ru: 'размер',
                fi: 'koko',
                et: 'maht',
            },
            price: {
                en: 'price',
                ru: 'цена',
                fi: 'hinta',
                et: 'hind',
            },
            beer: {
                en: '★beer★',
                ru: '★пиво★',
                fi: '★olut★',
                et: '★õlu★',
            },
            cider: {
                en: 'cider and long drink',
                ru: 'сидры',
                fi: 'siideri',
                et: 'siider',
            },
            soft_drinks: {
                en: 'soft drinks',
                ru: 'холодные напитки',
                fi: 'virvoitusjuomat',
                et: 'karastusjoogid',
            },
        },
        starters: {
            key: "starters",
            ru: "закуски",
            en: "starters",
            et: "eelroad",
            fi: "alkuruoat"
        },
        grill: {
            key: "grill",
            ru: "гриль и жареное",
            en: "grill & pan",
            et: "grill & pan", // заменить?
            fi: "grillistä ja pannulta"
        },
        desert: {
            key: "desert",
            ru: "десерт",
            en: "desserts",
            et: "dessert",
            fi: "jälkiruoat"
        },
        soups: {
            key: "soups",
            ru: "супы",
            en: "soups",
            et: "supid",
            fi: "keitot"
        },
        drinks :{
            key: "drinks",
            ru: "Напитки",
            en: "Drinks",
            et: "Joogid",
            fi: "Juomat"
        },
        special: {
            key: "special",
            ru: "Трапеза по-Выборгски",
            en: "Wiipuri Relish",
            et: "Wiipuri Hõrgutis",
            fi: "Wiipurilainen Herkkuateria"
        },
        group: {
            key: "group",
            ru: "Групповое меню",
            en: "Group menu",
            et: "Rühmamenüü",
            fi: "Ryhmämenu"
        },
        feast: {
            key: "feast",
            ru: "Рождественский пир",
            en: "The Christmas feast",
            et: "Jõulusööming",
            fi: "Joulusyöminki"
        },
        menu: {
            key: "menu",
            ru: "Меню",
            en: "Menu",
            et: "Menüü",
            fi: "Menu"
        },
        gallery: {
            key: "gallery",
            ru: "Галерея",
            en: "Gallery",
            et: "Galerii",
            fi: "Galleria"
        },
        chiefRec: {
            key: "chief",
            ru: "от шеф-повара",
            en: "chief recommends",
            et: "peakokk soovitab",
            fi: "pääkokki suosittelee"
        },
        marskinpickles: {
            price: "5,0",
            key: "pickles",
            ru: {name: "солёные огурчики Вальсберга", desc: "малосольные огурцы / черемша / сметана / медово-горчичный соус / рюмка водки"},
            et: {name: "walsberg'i soolakurgid", desc: "marineeritud karulauk / hapukoor / mee-sinepikaste / klaas viina"},
            fi: {name: "walsberg'in suolakurkku", desc: "karhunlaukkaa / smetanaa / hunaja-sinappikastiketta / marskin ryypy"},
            en: {name: "walsberg's salted pickles", desc: "ramsons / sour cream / honey-mustard sauce / marshall's vodka shot"},
        },
        christmas_header_1: {
            key: "christmasheader1",
            ru: "На закуску гостей ожидает:",
            fi: "Alkupalaksi vierailijoita on pöydässä odotamassa:",
            en: "As guests arrive, the table will be covered with various appetizers:",
            et: "Eelroogadest on laual külalisi ootamas:",
        },
        christmas_header_2: {
            key: "christmasheader2",
            ru: "На горячее на стол вынесут:",
            fi: "Pääruoaksi pöydälle tuodaan:",
            en: "After that, the main courses will be served:",
            et: "Pearoogadena tuuakse lauale:"
        },
        christmas_header_3: {
            key: "christmasheader3",
            ru: "В завершении трапезы предлагаем сладкое:",
            fi: "Hauskan illallisen lopuksi tarjoillaan jälkiruoka:",
            en: "The merry feast will come to an end with dessert:",
            et: "Lõbusa söömaaja lõpetuseks pakume magusrooga:"
        },
        christmas_summary: {
            key: "christmassummary",
            ru: "Предлагаем компании начиная с 8 человек. Цена на одного человека 34.90",
            fi: "Minimi henkilömäärä 8 henkeä. Illallisen hinta 34.90 euroa (ei sisältää juomia)",
            en: "Feast starting from 8 guests. Price per guest 34.90",
            et: "Pakume seltskonnale alates 8 inimesest. Hind külalise kohta 34.90. Söömaaja hind ei sisalda jooke"
        },
        christmas_starter: {
            key: "christmasstarter",
            ru: ['Солёные огурцы с медово-горчичным соусом и сметаной',
            'Рыбное ассорти из солёного сига, маринованной селёдки и слабосолёное филе лосося',
            'Мясное ассорти из ростбифа, запечённая баранья нарезка и восхитительный мясной паштет',
            'Запечённая до золотистой корочки кулебяка с лососем, рисом и сливочным сыром',
            'Драники из свеклы с соусом из йогурта'],
            fi: ['Suolakurkkuja smetanan ja hunaja-sinappikastikkeen kera',
            'Kalavalikoimassa suolattua siikaa, marinoitua silliä ja kevyesti suolattua lohta',
            'Lihavalikoimassa vaaleanpunaista paahtopaistia, kypsennettyjä lampaanlihaviipaleita ja herkullista lihapateeta',
            'Kultaruskeaksi kypsennettyä lohipiirakkaa riisi- ja tuorejuustotäytteellä',
            'Punajuuripihvejä jogurttikastikkeen kera'],
            en: ['Salted pickles with honey-mustard sauce and sour cream',
            'Salted whitefish, marinated herring and salt cured salmon',
            'Tender roast beef, delicate meat pâté and slices of roasted lamb',
            'Golden brown salmon coulibiac with rice and cream cheese stuffing',
            'Beetroot fritters with yoghurt sauce'],
            et: ['Soolakurgid mee-sinepikastme ja hapukoorega',
            'Kalavalikus soolasiig, marineeritud heeringas ja kergelt soolatud lõhefilee',
            'Lihavalikus õrnroosa rostbiif, küpsetatud lambalihalõigud ja hõrk lihapatee',
            'Kuldseks küpsetatud lõhekulebjaaka riisi- ja toorjuustutäidisega',
            'Peedikotletid jogurtikastmega'],
        },
        christmas_main: {
            key: "christmasmain",
            ru: ['Тушёный окорок в горчичном соусе',
            'Филе трески панированное в пармезане с каперсами и лимонно-сливочный соус',
            'Картофель запечённый с тмином',
            'Тушёная красная капуста с мёдом'],
            fi: ['Sinappikastikkeessa haudutettua porsaanpotkaa',
            'Parmesaanilla ja kapriksilla paneroitua turskafileetä kermaisen sitruunakastikkeen kera',
            'Uunikypsennettyjä kuminaperunoita',
            'Hunajalla haudutettua punakaalia'],
            en: ['Piglet legs poached in mustard sauce',
            'Cod fillet breaded with parmesan and capers accompanied by creamy lemon sauce',
            'Oven baked cumin potatoes',
            'Red cabbage braised with honey'],
            et: ['Sinepikastmes hautatud sea minikoot',
            'Parmesani-kapparipaneeringus tursafilee sidruni-koorekastmega',
            'Ahjuküpsed köömnekartulid',
            'Meega hautatud punakapsas'],
        },
        christmas_end: {
            key: "christmasend",
            ru: ['Запечённое яблоко с мёдом и лимонным парфе',
            'Вода с клюквой и чабрецом',
            'Чай или кофе'],
            fi: ['Uuniomenoita sitruunaparfeen kera',
            'Teetä/kahvia',
            'Jäävettä timjamin ja karpaloiden kera'],
            en: ['Oven baked apple with lemon parfait',
            'Tea/coffee',
            'Water with thyme and cranberries'],
            et: ['Meega küpsetatud ahjuõun sidruniparfeega',
            'Tee/kohv',
            'Jäävesi tüümiani- ja jõhvikatega'],
        },
        governor_title: {
            key:"governortitle",
            ru: "Трапеза Губернатора",
            et: "Kuberneri sööming",
            fi: "Kuvernöörin syöminki",
            en: "The Governor’s feast",
        },
        governor_header1: {
            key:"governorheader1",
            ru: "Ваш пир вы можете начать с закусок:",
            et: "Eelroogadest on laual külalisi ootamas:",
            fi: "Alkupalaksi vierailijoita on pöydässä odotamassa:",
            en: "As guests arrive, the table will be covered with various appetizers:",
        },
        governor_header2: {
            key:"governorheader2",
            ru: "Из основных блюд предлагаем:",
            et: "Pearoogadena tuuakse lauale:",
            fi: "Pääruoaksi pöydälle tuodaan:",
            en: "After that, the main courses will be served:",
        },
        governor_header3: {
            key: "governorheader3",
            ru: "Трапезу заканчивает десерт:",
            et: "Lõbusa söömaaja lõpetuseks pakume magusrooga:",
            fi: "Hauskan illallisen lopuksi tarjoillaan jälkiruoka:",
            en: "The merry feast will come to an end with dessert:",
        },
        governor_summary: {
            key: "governorsummary",
            ru: "Предложение для группы из 8 человек и более. Цена на человека 28.90",
            et: "Grupimenüü alates 8 inimesest. Hind külalise kohta 28.90",
            fi: "Illallisen hinta 28.90 euroa (ei sisältää juomia)",
            en: "Group menu starting from 8 guests. Price per guest 28.90",
        },
        governor_start: {
            key: "governorstart",
            ru: ["Солёные огурчики с медово горчичным соусом и сметаной",
            "Домашний пирог с лисичками и картофелем",
            "Ассорти из морепродуктов: маринованная сельд, солёный лосось, крем из тунца в круглых хлебцах",
            "Мясное ассорти: нежные кусочки говядины, говяжий язык на гриле, испеченные маринованные кусочки курицы",
            "свежий салат из овощей с курицей и лисичками в пикантном соусе",],
            et: ["Soolakurgid mee-sinepikastme ja hapukoorega",
            "Kodune kartuli-kukeseenepirukas",
            "Kalavalikus marineeritud heeringas, õrnalt soolatud lõhefilee ja tuunikalasalatiga rukkileivakorvid",
            "Lihavalikus õrnroosa rostbiif, kergelt suitsune veisekeel ja marineeritud küpsetatud kanafileelõigud",
            "Värske roheline salat kanafilee, kukeseente, sobilike köögiviljade ja kreemja kastmega",],
            fi: ["Suolakurkkuja smetanan ja hunaja-sinappikastikkeen kanssa",
                "Kotoista peruna-kantarellipiirakkaa",
                "Kalavalikoimassa marinoitua silliä, kevyesti suolattua lohta ja tonnikalasalaattia ruisleipäkoreissa.",
                "Lihavalikoimassa vaaleanpunaista paahtopaistia, kevyesti savustettua naudankieltä ja marinoituja kananfileeviipaleita",
                "Tuoresta vihreän salaattin valikoimaa grillatun kananfileen, kantarellien, sopivien vihannesten ja kermaisen kastikkeen kera"],
            en: ["Salted pickles with honey-mustard sauce and sour cream",
            "Home made potato-chanterelle pie",
            "Marinated herring, lightly salted salmon and rye bread baskets filled with tuna cream",
            "Tender roast beef, mildly smoked beef tongue and slices of marinated and cooked chicken breast",
            "Fresh salad with chicken fillet and chanterelles accompanied by suitable vegetables and creamy sauce"],
        },
        governor_main: {
            key: "governormain",
            ru: ["Запеченный свиной карбонат на косточке",
                "Запеченная камбала в соусе подается на горячеи сковороде",
                "До золотой корочки запеченный картофель и пряный рис",
                "Тёплый салат из красной капусты",
                "Сливочно грибной соус"],
            et: ["Kerges suitsus küpsetatud seakarree",
                "Kuumal malmpannil kastmes küpsetatud lestavorm",
                "Kuldpruunid küpsekartulid ja ürdine riis",
                "Soe punakapsasalat",
                "Koorene metsaseenekaste"],
            fi: ["Kevyessä savussa kypsennetyä siankylkeä",
            "Kuumalla valurautapannulla kastikkeessa kypsennetyä kampelavuokaa",
            "Kultaruskeaksi kypsennettyjä perunoita ja yrteillä maustettua riisiä",
            "Kuumaa punakaalisalaattia",
            "Kermaista metsäsienikastikkeetta"],
            en: ["Pork rack cooked in tender smoke",
            "Flounder casserole served on hot cast iron pan",
            "Oven baked golden brown potatoes and herby rice",
            "Hot red cabbage salad",
            "Creamy mushroom sauce"],
        },
        governor_end: {
            key: "governorend",
            ru: ["Медовик с клюквенным соусом и мороженым",
                "Чай/кофе"],
            et: ["Meekook jõhvikakastme ja jäätisega",
                "Tee/kohv"],
            fi: ["Hunajakakkua jäätelön ja karpalokastikkeen kera",
            "Teetä/kahvia"],
            en: ["Honey cake with raspberry sauce and ice cream",
            "Tea/coffee"],
        },
        // EMPEROR
        emperor_title: {
            key:"emperortitle",
            ru: "Трапеза Императора",
            et: "Imperaatori sööming",
            fi: "Imperaattori syöminki",
            en: "The Emperor’s feast",
        },
        emperor_header1: {
            key:"emperorheader1",
            ru: "Ваш пир вы можете начать с закусок:",
            et: "Eelroogadest on laual külalisi ootamas:",
            fi: "Alkupalaksi vierailijoita on pöydässä odotamassa:",
            en: "As guests arrive, the table will be covered with various appetizers:",
        },
        emperor_header2: {
            key:"emperorheader2",
            ru: "Из основных блюд предлагаем:",
            et: "Pearoogadena tuuakse lauale:",
            fi: "Pääruoaksi pöydälle tuodaan:",
            en: "After that, the main courses will be served:",
        },
        emperor_header3: {
            key: "emperorheader3",
            ru: "Трапезу заканчивает десерт:",
            et: "Tõhusa eine lõpuks serveeritakse magustoit:",
            fi: "Hauskan illallisen lopuksi tarjoillaan jälkiruoka:",
            en: "The merry feast will come to an end with dessert:",
        },
        emperor_summary: {
            key: "emperorsummary",
            ru: "Предложение для группы из 8 человек и более. Цена на человека 37.90",
            et: "Grupimenüü alates 8 inimesest. Hind külalise kohta 37.90",
            fi: "Illallisen hinta 37.90 euroa (ei sisältää juomia)",
            en: "Group menu starting from 8 guests. Price per guest 37.90 euro",
        },
        emperor_start: {
            key: "emperorstart",
            ru: ["Солёные огурчики с медово горчичным соусом и сметаной",
                "Золотистый пирог со шпинатом и сыром",
                "Ассорти из морепродуктов: лосось холодного копчения, маринованные  тигровые креветки на гриле, жаренные миноги в желе и маринованные кусочки щуки",
                "Мясное ассорти: кусочки утки на гриле, овощями фаршированный свиной карбонад, мясное пате и сало",
                "Салат с кусочками говядины на гриле, овощями и шампиньонами"],
            et: ["Soolakurgid mee-sinepikastme ja hapukoorega",
                "Kuldpruun spinati ja juustutäidisega pirukas",
                "Kalavalikus külmsuitsulõhe, marineeritud ja grillitud hiidkrevetid, röstitud silmud tarrendis ja marineeritud haugifileeribad",
                "Lihavalikus grillitud pardirind, köögiviljadega pikitud küpsetatud seakaelakarbonaad, hõrk lihapatee ja soolatud seapekk",
                "Salat grillitud veise sisefilee, köögiviljade ja šampinjonidega"],
            fi: ["Suolakurkkuja smetanan ja hunaja-sinappikastikkeen kanssa",
            "Kultaruskeaksi kypsennetyä pinaatti-juustopiirakkaa",
            "Kalavalikoimassa kylmäsavulohta, marinoituja grillatuja jättikatkarapuja, paahdettuja nahkiaisia ja marinoituja haukifileen suikaleita",
            "Lihavalikoimassa grillatua ankanrintaa, vihanneksilla täytettyä kypsennettyä porsaankyljystä, herkullista lihapateeta ja suolattua läskiä",
            "Salaattia grillatun naudan sisäfileen, vihanneksien ja herkkusienien kanssa"],
            en: ["Salted pickles with honeymustard sauce and sour cream",
            "Golden brown pie filled with spinach and cheese",
            "Coldsmoked salmon, marinated and grilled tiger prawns, roasted lampreys in jelly and marinated pike",
            "Grilled duck breast, pork chop stuffed with vegetables, tender meat pâté and salted lard",
            "Fresh salad with grilled beef tenderloin, vegetables and champignons"],
        },
        emperor_main: {
            key: "emperormain",
            ru: ["Рулет из говядины фаршированный морковью и спаржeй",
                "Целиком запечённая форель с рисом и оващями",
                "Картофель запеченный с приправами и гречка",
                "Овощи с шампиньонами на гриле",
                "Винный соус",
                "Сливочный соус с перцем и медом"],
            et: ["Porgandi ja spargliga täidetud veiseliharulaad",
                "Juurviljariisiga täidetud tervelt küpsetatud forell",
                "Küpsetatud ürdikartulid ja tatrapuder",
                "Grillitud juurviljad shampinjonidega",
                "Veinikaste",
                "Koorene mee-piprakaste"],
            fi: ["Porkkanalla ja parsalla täytettyä naudanlihakääryletä",
            "Vihannesriisillä täytettyä kokonaisena kypsennettyä taimenta",
            "Uuniruskeita yrttiperunoita ja tattaripuuroa",
            "Grillatuja vihanneksia ja herkkussieniä",
            "Viinikastiketta",
            "Kermaista hunaja-pippurikastiketta"],
            en: ["Beef roulade stuffed with carrots and asparagus",
            "Oven cooked trout filled with rice and vegetables",
            "Golden herb potatoes and buckwheat porridge",
            "Grilled vegetables and champignons",
            "Red wine sauce",
            "Creamy honeypepper sauce"],
        },
        emperor_end: {
            key: "emperorend",
            ru: ["Пирог Наполеон с лимонным парфе и соусом из ягод",
            "Чай/кофе"],
            et: ["„Napoleoni“  kook sidruniparfee ja marjakastmega",
            "Tee/kohv"],
            fi: ["„Napoleon“ kakkua sitruunaparfeen ja marjakastiken kera",
            "Teetä/kahvia" ],
            en: ["„Napoleon“ cake with lemon parfait and berry sauce",
            "Tea/coffee"],
        },

        
    },
    drinks: {
        soft_drinks: {
            cola: {
                key: 'cola',
                price: '2,9',
                ru: 'Coca-cola',
                et: 'Coca-cola',
                fi: 'Coca-cola',
                en: 'Coca-cola',
                amount: '0,25',
                unit: 'l',
            },
            colazero: {
                key: 'colazero',
                price: '2,9',
                ru: 'Coca-cola Zero',
                et: 'Coca-cola Zero',
                fi: 'Coca-cola Zero',
                en: 'Coca-cola Zero',
                amount: '0,25',
                unit: 'l',
            },
            fanta: {
                key: 'fanta',
                price: '2,9',
                ru: 'Fanta',
                et: 'Fanta',
                fi: 'Fanta',
                en: 'Fanta',
                amount: '0,25',
                unit: 'l',
            },
            sprite: {
                key: 'sprite',
                price: '2,9',
                ru: 'Sprite',
                et: 'Sprite',
                fi: 'Sprite',
                en: 'Sprite',
                amount: '0,25',
                unit: 'l',
            },
            kali: {
                key: 'kali',
                price: '3,1',
                ru: 'Квас',
                et: 'Kali',
                fi: 'Kvass', // KEEP?!
                en: 'Kvass',
                amount: '0,5',
                unit: 'l',
            },
            nestea: {
                key: 'nestea',
                price: '3,1',
                ru: 'Холодный чай Nestea',
                et: 'Jäätee Nestea',
                fi: 'Jäätee Nestea',
                en: 'Nestea Ice Tea',
                amount: '0,3',
                unit: 'l',
            },
            juice: {
                key: 'juice',
                price: '3,0',
                ru: 'Сок',
                et: 'Mahl',
                fi: 'Mehu',
                en: 'Juice',
                amount: '0,33',
                unit: 'l',
            },
            water: {
                key: 'water',
                price: '2,9',
                ru: 'Vichy',
                et: 'Vichy',
                fi: 'Vichy',
                en: 'Vichy',
                amount: '0,33',
                unit: 'l',
            },
            tonic: {
                key: 'tonic',
                price: '2,9',
                ru: 'Tonic water',
                et: 'Tonic water',
                fi: 'Tonic water',
                en: 'Tonic water',
                amount: '0,25',
                unit: 'l',
            },
            ginger: {
                key: 'ginger',
                price: '2,9',
                ru: 'Ginger Ale',
                et: 'Ginger Ale',
                fi: 'Ginger Ale',
                en: 'Ginger Ale',
                amount: '0,25',
                unit: 'l',
            },
            battery: {
                key: 'battery',
                price: '4,5',
                ru: 'Battery',
                et: 'Battery',
                fi: 'Battery',
                en: 'Battery',
                amount: '0,33',
                unit: 'l',
            },
        },
        tequila: {
            sierra_silver: {
                key: 'sierra_silver',
                price: '5,5',
                name: 'Sierra Silver',
                amount: '4',
                unit: 'cl',
            },
            sierra_anejo: {
                key: 'sierra_antiguo_anejo',
                price: '5,9',
                name: 'Sierra Antiguo Añejo',
                amount: '4',
                unit: 'cl',
            }
        },
        gin: {
            finsbury: {
                key: 'finsbury',
                price: '5,0',
                name: 'Finsbury Dry',
                amount: '4',
                unit: 'cl',
            },
            sierra_anejo: {
                key: 'sierra_antiguo_anejo',
                price: '5,9',
                name: 'Sierra Antiguo Añejo',
                amount: '4',
                unit: 'cl',
            },
        },
        beer: {
            big_lager: {
                key: 'big_lager',
                price: '8,9',
                name: 'Wana Wiipuri Lager',
                amount: '1',
                unit: 'l',
            },
            lager: {
                key: 'lager',
                price: '4,9',
                name: 'Wana Wiipuri Lager',
                amount: '0,5',
                unit: 'l',
            },
            small_lager: {
                key: 'small_lager',
                price: '4,0',
                name: 'Wana Wiipuri Lager',
                amount: '0,33',
                unit: 'l',
            },
            dark_lager: {
                key: 'dark_lager',
                price: '4,9',
                name: 'Wana Wiipuri Dark/Herb',
                amount: '0,5',
                unit: 'l',
            },
            corona: {
                key: 'corona',
                price: '4,3',
                name: 'Corona',
                amount: '0,33',
                unit: 'l',
            },
            muddis: {
                key: 'muddis',
                price: '4,8',
                name: 'Muddis IPA/Golden Ale',
                amount: '0,33',
                unit: 'l',
            },
            schoffer: {
                key: 'schoffer',
                price: '4,9',
                name: 'Schöfferhofer Weizen',
                amount: '0,33',
                unit: 'l',
            },
            nabeer: {
                key: 'nabeer',
                price: '4,5',
                name: 'Puls Lager Alcohol-free',
                amount: '0,5',
                unit: 'l',
            },
        },
        cider: {
            dryapple: {
                key: 'dryapple',
                price: '4,9',
                name: 'Puls Premium Dry Apple',
                amount: '0,33',
                unit: 'l',
            },
            pear: {
                key: 'pear',
                price: '4,9',
                name: 'Puls Pear',
                amount: '0,33',
                unit: 'l',
            },
            bouche: {
                key: 'bouche',
                price: '14,5',
                name: 'Cidre Bouche Brut de Normandie',
                amount: '0,75',
                unit: 'l',
            },
            long: {
                key: 'long',
                price: '4,9',
                name: 'Long Drink',
                amount: '0,33',
                unit: 'l',
            },
        },
        hot: {
            tea: {
                key: 'tea',
                price: '3,0',
                name: 'Tea',
            },
            coffee: {
                key: 'coffee',
                price: '2,9',
                name: 'Coffee',
            },
            espresso: {
                key: 'espresso',
                price: '2,9',
                name: 'Espresso',
            },
            cappuccino: {
                key: 'cappuccino',
                price: '3,6',
                name: 'Cappuccino',
            },
            latte: {
                key: 'latte',
                price: '3,9',
                name: 'Cafe Latte',
            },
            irish: {
                key: 'irish',
                price: '6,9',
                name: 'Irish Coffee',
            },
            vt_coffee: {
                key: 'vt_coffee',
                price: '6,8',
                name: 'Vana Tallinn Coffee',
            },
            ww_coffee: {
                key: 'ww_coffee',
                price: '6,9',
                name: 'Wana Wiipuri Coffee',
            },
        },
        vodka: {
            sobieski: {
                key: 'sobieski',
                price: '3,9',
                name: 'Sobieski Premium',
                amount: '4',
                unit: 'cl',
            },
            lp_dill: {
                key: 'lp_dill',
                price: '4,9',
                name: 'L&P Dill',
                amount: '4',
                unit: 'cl',
            },
            marskin: {
                key: 'marskin',
                price: '5,5',
                name: 'Marskin Ryypy',
                amount: '4',
                unit: 'cl',
            },
            russkaya: {
                key: 'russkaya',
                price: '4,3',
                name: 'Russkaya',
                amount: '4',
                unit: 'cl',
            },
            grand_thomas: {
                key: 'grand_thomas',
                price: '4,8',
                name: 'Grand Thomas',
                amount: '4',
                unit: 'cl',
            },
            saaga: {
                key: 'saaga',
                price: '4,9',
                name: 'Saaga',
                amount: '4',
                unit: 'cl',
            },
            moe_vodka: {
                key: 'moe_vodka',
                price: '4,5',
                name: 'Moe Vodka',
                amount: '4',
                unit: 'cl',
            },
            moe_goldenroot: {
                key: 'moe_goldenroot',
                price: '5,5',
                name: 'Moe Golden Root',
                amount: '4',
                unit: 'cl',
            },
            moe_chilli: {
                key: 'moe_chilli',
                price: '5,5',
                name: 'Moe Chilli',
                amount: '4',
                unit: 'cl',
            },
            tamula_vanake: {
                key: 'tamula_vanake',
                price: '5,7',
                name: 'Tamula Vanake (Moonshine)',
                amount: '4',
                unit: 'cl',
            },
        },
        cognac: {
            vsop: {
                key: 'vsop',
                price: '7,5',
                name: 'Chateau di Montifaud VSOP',
                amount: '4',
                unit: 'cl',
            },
            xo: {
                key: 'xo',
                price: '17,9',
                name: 'Chateau di Montifaud XO',
                amount: '4',
                unit: 'cl',
            },
            metaxa: {
                key: 'metaxa',
                price: '5,3',
                name: 'Metaxa 7*',
                amount: '4',
                unit: 'cl',
            },
            boncourt: {
                key: 'boncourt',
                price: '4,9',
                name: 'Boncourt XO',
                amount: '4',
                unit: 'cl',
            },
        },
        liquer: {
            vana_tallinn: {
                key: 'vana_tallinn',
                price: '4,8',
                name: 'Vana Tallinn',
                amount: '4',
                unit: 'cl',
            },
            jagtraum: {
                key: 'jagtraum',
                price: '4,7',
                name: 'Jagtraum',
                amount: '4',
                unit: 'cl',
            },
            kannukukk: {
                key: 'kannukukk',
                price: '4,9',
                name: 'Kännu Kukk',
                amount: '4',
                unit: 'cl',
            },
            kristall: {
                key: 'kristall',
                price: '5,1',
                name: 'Kristallkümmel',
                amount: '4',
                unit: 'cl',
            },
            amaretto: {
                key: 'amaretto',
                price: '4,7',
                name: 'Amaretto',
                amount: '4',
                unit: 'cl',
            },
            amaro: {
                key: 'amaro',
                price: '4,5',
                name: 'Amaro Averna',
                amount: '4',
                unit: 'cl',
            },
            holiday: {
                key: 'holiday',
                price: '5,3',
                name: 'Holiday Cream',
                amount: '4',
                unit: 'cl',
            },
            sambuca: {
                key: 'sambuca',
                price: '4,5',
                name: 'Sambuca',
                amount: '4',
                unit: 'cl',
            },
            pisang: {
                key: 'pisang',
                price: '4,5',
                name: 'Pisang',
                amount: '4',
                unit: 'cl',
            },
            marie: {
                key: 'marie',
                price: '4,5',
                name: 'Marie Brizard Cafe',
                amount: '4',
                unit: 'cl',
            },
            cointreau: {
                key: 'cointreau',
                price: '5,0',
                name: 'Cointreau',
                amount: '4',
                unit: 'cl',
            },
            marnier: {
                key: 'marnier',
                price: '5,0',
                name: 'Grand Marnier',
                amount: '4',
                unit: 'cl',
            },
        },
        whiskey: {
            lauders: {
                key: 'lauders',
                price: '5,2',
                name: 'Lauder\'s',
                amount: '4',
                unit: 'cl',
            },
            medleys: {
                key: 'medleys',
                price: '5,3',
                name: 'John Medley\'s',
                amount: '4',
                unit: 'cl',
            },
            black_label: {
                key: 'blacklabel',
                price: '7,3',
                name: 'Black Label',
                amount: '4',
                unit: 'cl',
            },
            islay_mist: {
                key: 'islay_mist',
                price: '7,9',
                name: 'Islay Mist Peated Blend Scotch',
                amount: '4',
                unit: 'cl',
            },
            bushmills: {
                key: 'bushmills',
                price: '5,0',
                name: 'Bushmill\'s Original',
                amount: '4',
                unit: 'cl',
            },
        },
        armagnac: {
            armagnac: {
                key: 'armagnac',
                price: '5,5',
                name: 'Armagnac Saint Christeau VSOP',
                amount: '4',
                unit: 'cl',
            },
            calvados: {
                key: 'calvados',
                price: '5,6',
                name: 'Calvados Papidoux VSOP',
                amount: '4',
                unit: 'cl',
            },
        },
        rum: {
            ron: {
                key: 'ron',
                price: '6,9',
                name: 'Ron Abuelo 7YO',
                amount: '4',
                unit: 'cl',
            },
            pascas_white: {
                key: 'pascas_white',
                price: '4,7',
                name: 'Old Pascas White',
                amount: '4',
                unit: 'cl',
            },
            pascas_dark: {
                key: 'pascas_dark',
                price: '4,8',
                name: 'Old Pascas Dark',
                amount: '4',
                unit: 'cl',
            },
        },
    },
    starters: {
        pickles: {
            price: "5,0",
            key: "pickles",
            ru: {name: "солёные огурчики Вальсберга", desc: "малосольные огурцы / черемша / сметана / медово-горчичный соус"},
            et: {name: "walsberg'i soolakurgid", desc: "marineeritud karulauk / hapukoor / mee-sinepikaste"},
            fi: {name: "walsberg'in suolakurkku", desc: "karhunlaukkaa / smetanaa / hunaja-sinappikastiketta"},
            en: {name: "walsberg's salted pickles", desc: "ramsons / sour cream / honey-mustard sauce"},
        },
        
        vorschmack: {
            price: "8,9",
            key: "vorschmack",
            ru: {name: "форшмак", desc: "запечёная свекла / корнишоны / сметана"},
            et: {name: "vorschmack", desc: "peedikreem / cornichonid / toorjuustuvaht"},
            fi: {name: "vorschmack", desc: "punajuurikermaa / suolakurkkua / tuorejuustovaahtoa"},
            en: {name: "vorschmack", desc: "beetroot cream / gherkins / cream cheese foam"},
        },
        vege : {
            price: "8,9",
            key: "vege",
            ru: {name: "овощи на гриле", desc: "маринованные овощи / сыр брынза / запечённая свекла"},
            et: {name: "vege", desc: "marineeritud köögiviljad / brõnsa juust / peedikreem"},
            fi: {name: "vege", desc: "marinoituja vihanneksia / bryndza-juustoa / punajuurikermaa"},
            en: {name: "vege", desc: "marinated vegetables / bryndza cheese / beetroot cream"},
        },
        caviar: {
            price: "9,8",
            key: "caviar",
            ru: {name: "икра и салат с грибами", desc: "красная икра / лесные грибы / сметана / лук / сухарики"},
            et: {name: "kalamari ja metsaseenesalat", desc: "sibul / hapukoor / röstsai"},
            fi: {name: "mäti ja metsäsienisalaatti", desc: "sipulia / smetanaa / paahtoleipää"},
            en: {name: "red caviar and mushroom salad", desc: "onion / sour cream / toast bread"},
        },
        seaselection: {
            price: "16,9",
            key: "seafood",
            ru: {name: "ассорти из морепродуктов", desc: "(хватает на двоих) солёный лосось / соус из тунца / копчёная селёдка / икра форели / икра сельди"},
            et: {name: "mereannivalik", desc: "(jätkub ka kahele) soolalõhe / tuunikalakreem / suitsuheeringas / forellimari / herringamari"},
            fi: {name: "merenantimia", desc: "(riittää kahdelle) graavilohta / tonnikalakastiketta / savusilliä / taimenenmätiä / sillimätiä"},
            en: {name: "seafood selection", desc: "(enough for two) salted salmon / tuna cream / smoked herring / trout roe / herring roe"},
        },
        meatselection: {
            price: "14,6",
            key: "meatselection",
            ru: {name: "мясное ассорти", desc: "(хватает на двоих) говяжий язык / копченая утка / мясной паштет / сало"},
            et: {name: "lihavalik", desc: "(jätkub ka kahele) veisekeel / pardifilee / lihapatee / soolapekk"},
            fi: {name: "lihavalikoima", desc: "(riittää kahdelle) naudankieltä / ankanrintaa / lihapateeta / suolasilavaa"},
            en: {name: "meat selection", desc: "(enough for two) veal tongue / duck breast / meat pate / salted lard"},
        },
        veal: {
            price: "8,5",
            key: "vealsalad",
            ru: {name: "салат с говядиной", desc: "говяжья вырезка / маринованные овощи / шампиньоны / листья салата"},
            et: {name: "vesiselihasalat", desc: "veise sisefilee / marineeritud köögiviljad / šampinjonid"},
            fi: {name: "naudanlihasalaatti", desc: "naudan sisäfilettä / marinoituja vihanneksia / herkkusieniä"},
            en: {name: "veal salad", desc: "beef tenderloin / marinated vegetables / champignons"},
        },
        caesar: {
            price: "7,9",
            key: "caesar",
            ru: {name: "цезарь по-выборгски", desc: "куриное филе / жареные лисички / лук порей / пармезан / хлебная крошка / соус цезарь"},
            et: {name: "caesar a'la wiipuri", desc: "kanafilee / kukeseened / parmesan / krutoonid"},
            fi: {name: "caesar a'la wiipuri", desc: "kanafilettä / kantarelleja / parmesaanijuustoa / krutonkeja"},
            en: {name: "caesar a'la wiipuri", desc: "chicken fillet / chanterelles / parmesan / croutons"},
        },
        tartar: {
            price: "13,9",
            key: "tartar",
            ru: {name: "тартар из говядины", desc: "филе говядины / солёные огурцы / лук / анчоусы / тосты / острый соус"},
            et: {name: "böff a'la tartar", desc: "sibul / soolakurk / anšoovis / röstsai / terav kaste"},
            fi: {name: "tartarpihvi", desc: "sipulia / suolakurkkua / anjovista / paahtoleipää / terävää kastiketta"}, // check if correct (last 2)
            en: {name: "beef a'la tar-tar", desc: "onion / gherkins / anchovy / toast bread / spicy sauce"},
        },
        herringtrio: {
            price: "8,6",
            key: "trio",
            ru: {name: "трио из селёдки", desc: "копчёная селёдка / парфе из селёдки / икра селёдки"},
            et: {name: "heeringatrio", desc: "suitsuheeringas / heeringaparfee / heeringamari"},
            fi: {name: "sillikolmikko", desc: "savusilliä / silliparfeetta / sillimätiä"},
            en: {name: "herring trio", desc: "smoked herring / herring parfait / herring roe"},
        },
        balticherring: {
            price: "6,5",
            key: "baltic",
            ru: {name: "салака", desc: "маринованный лук / яйцо 62C°"},
            et: {name: "räimed", desc: "marineeritud sibul / muna 62C°"},
            fi: {name: "silakka", desc: "marinoitua sipulia / munaa 62C°"},
            en: {name: "baltic herring", desc: "pickled onion / egg 62C°"},
        }
    },

    grill: {
        steak: {
            price: "22,9",
            key: "steak",
            ru: {name: "говядина по-выборгски", desc: "вырезка на гриле / вок из овощей / картофель с розмарином / винный соус"},
            et: {name: "wiipuri biifsteek", desc: "veise sisefilee / veinikaste / rosmariinikartul"},
            fi: {name: "wiipurilainen pihvi", desc: "naudan sisäfilettä / viinikastiketta / rosmariiniperunoita"},
            en: {name: "beefsteak wiipuri style", desc: "beef tenderloin / red wine sauce / rosemary potatoes"},
        },
        cheeks: {
            price: "18,8",
            key: "cheeks",
            ru: {name: "тушёные говяжьи щёки", desc: "тушеные говяжьи щёки / картофельный гратен / вишнёво-винный соус / свежий салат"},
            et: {name: "veisepõsk", desc: "hautatud veise põseliha / veini-kirsikaste / kartuligratään"}, // correct??
            fi: {name: "naudan poski", desc: "haudutettua naudan poskilihaa / viini-kirsikka-kastiketta / perunagratiinia"}, // and here ??
            en: {name: "beef cheek", desc: "braised beef cheek / wine and cherry sauce / potato gratin"},
        },
        duck: {
            price: "16,9",
            key: "duck",
            ru: {name: "утка", desc: "утиная грудка на гриле / малиновый соус / пюре из морковки"},
            et: {name: "part", desc: "grillitud pardirind / vaarikakaste / porgandipüree"},
            fi: {name: "ankka", desc: "grillatua ankanrintaa / vadelmakastiketta / porkkanasosetta"}, 
            en: {name: "duck", desc: "grilled duck breast / raspberry sauce / potato gratin"},
        },
        chicken: {
            price: "14,9",
            key: "chicken",
            ru: {name: "курица", desc: "куриное филе с косточкой / сырно-шпинатный соус / картофельный гратен"},
            et: {name: "kana", desc: "kanafilee supreme / juustu-spinatikaste / kartuligratään"},
            fi: {name: "kana", desc: "supreme kananrintaa / juusto-pinaattikastiketta / perunagratiinia"}, 
            en: {name: "chicken", desc: "chicken fillet supreme / cheese and spinach sauce / potato gratin"},
        },
        pork: {
            price: "15,9",
            key: "pork",
            ru: {name: "свиная мини-рулька", desc: "тушёная мини-рулька / яблочно-горчичный соус / картофельный гратен"},
            et: {name: "sea minikoot", desc: "hautatud seakoot / õuna-sinepikaste / kartuligratään"},
            fi: {name: "porsaanpotkaa", desc: "haudutettua porsanpotkaa / omena-sinappikastiketta / perunagratiinia"}, 
            en: {name: "pork", desc: "braised piglet knuckles / apple and mustard sauce / potato gratin"},
        },
        boar: {
            price: "18,6",
            key: "boar",
            ru: {name: "кабан", desc: "кабан тушёный в тёмном пиве / картофель с розмарином / овощи / свежий салат"},
            et: {name: "metssiga", desc: "tumedas õlles hautatud metssealiha / rosmariinikartul"},
            fi: {name: "villisika", desc: "tummassa oluessa haudutettua villisikaa / rosmariiniperunoita"}, 
            en: {name: "wild boar", desc: "wild boar meat braised in dark beer / rosemary potatoes"},
        },
        lamb: {
            price: "17,9",
            key: "lamb",
            ru: {name: "баранина", desc: "филе баранины на гриле / винный соус с мятой / ризотто с белыми грибами"},
            et: {name: "lammas", desc: "grillitud lambafilee / veini-mündikaste / puravikurisoto"},
            fi: {name: "lammas", desc: "grillattua lampaanfiletta / viini-minttukastiketta / tattirisottoa"}, 
            en: {name: "lamb", desc: "grillet lamb fillet / red wine and mint sauce / porcini risotto"},
        },
        hotpan: {
            price: "12,4",
            key: "hotpan",
            ru: {name: "горячая сковорода", desc: "запечённое мясо / картофель / лук / яйца / майонез"},
            et: {name: "kuum pann", desc: "ahjuliha / kartul / sibul / muna / majonees"},
            fi: {name: "kuuma pannu", desc: "lihaa / perunaa / sipulia / munaa / majoneesia"}, 
            en: {name: "hot pan", desc: "meat / potatoes / onion / egg / mayonnaise"},
        },
        perch: {
            price: "13,7",
            key: "perch",
            ru: {name: "окунь", desc: "филе окуня на гриле / ризотто с белыми грибами / масло с каперсами"},
            et: {name: "ahven", desc: "grillitud ahvenafilee / kapparivõi / puravikurisoto"},
            fi: {name: "ahven", desc: "grillattua ahventa / kaprisvoita / tattirisottoa"}, 
            en: {name: "perch", desc: "grilled perchfillet / caper butter sauce / porcini risotto"},
        },
        salmon: {
            price: "16,7",
            key: "salmon",
            ru: {name: "лосось", desc: "филе лосося на гриле / варёный картофель / сливочный соус с лимоном"},
            et: {name: "lõhe", desc: "grillitud lõhefilee / sidruni-võikaste / keedukartul"},
            fi: {name: "lohi", desc: "grillattua lohta / kerma-sitruunakastiketta / keitettyjä perunoita"}, 
            en: {name: "salmon", desc: "grilled salmon fillet / creamy lemon sauce / boiled potatoes"},
        },
    },
    soups: {
        borsch: {
            price: "6,4",
            key: "borsch",
            ru: {name: "борщ", desc: "говяжий язык / сметана"},
            et: {name: "borš", desc: "veisekeel / hapukoor"},
            fi: {name: "klassinen borssikeitto", desc: "naudankieltä / smetanaa"}, 
            en: {name: "borsch", desc: "veal tongue / sour cream"},
        },
        weeksoup: {
            price: "5,9",
            key: "weeksoup",
            ru: {name: "суп недели", desc: "информация у официанта"},
            et: {name: "nädalasupp", desc: "küsi teenindajatelt"},
            fi: {name: "viinon keitto", desc: "kysy tarjoilijalta"}, 
            en: {name: "soup of the week", desc: "ask your waiter"},
        },
    },
    desserts: {
        honeycake: {
            price: "5,9",
            key: "honeycake",
            ru: {name: "дуэт из медовика", desc: "медовик классический / медовик с какао / ягодный соус / взбитая сметана"},
            et: {name: "meekoogi duo", desc: "toorjuustuvaht / marjakaste"},
            fi: {name: "hunajakakku duo", desc: "tuorejuustovaahtoa / marjakastiketta"}, 
            en: {name: "honey cake duo", desc: "cream cheese mousse / berry sauce"},
        },
        pannacotta: {
            price: "5,9",
            key: "pannacotta",
            ru: {name: "панна котта", desc: "крем из йогурта / клюквенный соус"},
            et: {name: "panna cotta", desc: "jogurtikreem / jõhvikakaste"},
            fi: {name: "panna cotta", desc: "jogurttikermaa / karpalokastiketta"}, 
            en: {name: "panna cotta", desc: "yoghurt cream / cranberry sauce"},
        },
        chocolatecake: {
            price: "5,9",
            key: "chococake",
            ru: {name: "шоколадный пирог", desc: "желе из облепихи / малиновый соус"},
            et: {name: "šokolaadikook", desc: "astelpajuželee / vaarikakaste"},
            fi: {name: "suklaakakku", desc: "tyrnimarjahyytelä / vadelmakastiketta"}, 
            en: {name: "chocolate cake", desc: "sea buckthorn jelly / raspberry sauce"},
        },
        icecream: {
            price: "4,8",
            key: "icecream",
            ru: {name: "мороженое", desc: "ванильное / шоколадное / малиновое / ягодный соус"},
            et: {name: "jäätis", desc: "jäätisevalik / marjakaste"},
            fi: {name: "jäätelö", desc: "jäätelövalikoima / marjakastiketta"}, 
            en: {name: "ice cream", desc: "ice cream selection / berry sauce"},
        },
    }
   

}

export default data

